spring.application.name=esotericaClients

spring.datasource.url=jdbc:postgresql://localhost:5432/esoterica
spring.datasource.username=postgres
spring.datasource.password=Abc1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=CAMBIAR_ESTE_SECRETO_LARGO
app.jwt.expiration-minutes=60
