spring.application.name=esotericaClients

spring.datasource.url=jdbc:postgresql://localhost:5432/dbesoterica
spring.datasource.username=postgres
spring.datasource.password=Abc1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway

spring.flyway.enabled=true

# JPA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
