spring.application.name=esotericaClients

spring.datasource.url=jdbc:postgresql://localhost:5432/dbesoterica
spring.datasource.username=postgres
spring.datasource.password=Abc1234
spring.datasource.driver-class-name=org.postgresql.Driver

SECRET="347b777680ce26423debfd7d1c6c80b4d455caa3a85882a55c1ee3a7a6aadf06";

# Flyway

spring.flyway.enabled=true

# JPA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
